language: node_js
node_js: '8.9.4'
cache: yarn
notifications:
  email: false
install:
  - yarn
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
