language: node_js
node_js: '8.9.4'
cache: yarn
notifications:
  email: false
install:
  - yarn
script:
  - npm test
  - npm start
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
